module.exports = {
  apps: [
    {
      name: 'gateway',
      script: 'dist/apps/gateway/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      max_memory_restart: '256M',
      error_file: '/dev/stderr',
      out_file: '/dev/stdout',
      merge_logs: true,
      time: true,
    },
    {
      name: 'auth-service',
      script: 'dist/apps/auth-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      max_memory_restart: '256M',
      error_file: '/dev/stderr',
      out_file: '/dev/stdout',
      merge_logs: true,
      time: true,
    },
    {
      name: 'master-data-service',
      script: 'dist/apps/master-data-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      max_memory_restart: '256M',
      error_file: '/dev/stderr',
      out_file: '/dev/stdout',
      merge_logs: true,
      time: true,
    },
    {
      name: 'voucher-service',
      script: 'dist/apps/voucher-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
      },
      max_memory_restart: '256M',
      error_file: '/dev/stderr',
      out_file: '/dev/stdout',
      merge_logs: true,
      time: true,
    },
    {
      name: 'cash-book-service',
      script: 'dist/apps/cash-book-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
      },
      max_memory_restart: '256M',
      error_file: '/dev/stderr',
      out_file: '/dev/stdout',
      merge_logs: true,
      time: true,
    },
    {
      name: 'payable-service',
      script: 'dist/apps/payable-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3005,
      },
      max_memory_restart: '256M',
      error_file: '/dev/stderr',
      out_file: '/dev/stdout',
      merge_logs: true,
      time: true,
    },
    {
      name: 'reporting-service',
      script: 'dist/apps/reporting-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3006,
      },
      max_memory_restart: '256M',
      error_file: '/dev/stderr',
      out_file: '/dev/stdout',
      merge_logs: true,
      time: true,
    },
    {
      name: 'config-service',
      script: 'dist/apps/config-service/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3007,
      },
      max_memory_restart: '256M',
      error_file: '/dev/stderr',
      out_file: '/dev/stdout',
      merge_logs: true,
      time: true,
    },
  ],
};
