import { ChungTu } from '@/types';

// ===== PHIẾU THU =====

export const mockPhieuThu: ChungTu[] = [
  {
    id: '1',
    soPhieu: 'PT001/2024',
    loai: 'PHIEU_THU',
    ngay: '2024-01-15',
    soTien: 50000000,
    noiDung: 'Thu tiền bán hàng - Hợp đồng HD001',
    doiTuongId: '1',
    doiTuongTen: 'Công ty TNHH ABC',
    duAnId: '1',
    duAnTen: 'Xây dựng nhà máy ABC',
    chuDauTuTen: 'Công ty TNHH ABC',
    sanPhamId: '6',
    sanPhamTen: 'Dịch vụ tư vấn thiết kế',
    dongTienId: '1',
    dongTienTen: 'Thu từ bán hàng',
    taiKhoanNo: '1111',
    taiKhoanCo: '131',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Nguyễn Văn A',
    ngayTao: '2024-01-15',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-15',
  },
  {
    id: '2',
    soPhieu: 'PT002/2024',
    loai: 'PHIEU_THU',
    ngay: '2024-01-18',
    soTien: 25000000,
    noiDung: 'Thu tiền tạm ứng hoàn lại',
    doiTuongId: '8',
    doiTuongTen: 'Nguyễn Văn Hùng',
    boPhanId: '9',
    boPhanTen: 'Đội thi công số 1',
    doiId: '9',
    doiTen: 'Đội thi công số 1',
    nhanVienId: 'NV001',
    nhanVienTen: 'Nguyễn Văn Hùng',
    dongTienId: '2',
    dongTienTen: 'Thu từ công nợ phải thu',
    taiKhoanNo: '1111',
    taiKhoanCo: '141',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Nguyễn Văn A',
    ngayTao: '2024-01-18',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-18',
  },
  {
    id: '3',
    soPhieu: 'PT003/2024',
    loai: 'PHIEU_THU',
    ngay: '2024-01-20',
    soTien: 120000000,
    noiDung: 'Thu tiền bán hàng - Công ty XYZ',
    doiTuongId: '2',
    doiTuongTen: 'Công ty CP XYZ',
    duAnId: '2',
    duAnTen: 'Cải tạo văn phòng XYZ',
    chuDauTuTen: 'Công ty CP XYZ',
    sanPhamId: '7',
    sanPhamTen: 'Dịch vụ giám sát thi công',
    dongTienId: '1',
    dongTienTen: 'Thu từ bán hàng',
    taiKhoanNo: '1121',
    taiKhoanCo: '131',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Lê Văn C',
    ngayTao: '2024-01-20',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-21',
  },
  {
    id: '4',
    soPhieu: 'PT004/2024',
    loai: 'PHIEU_THU',
    ngay: '2024-01-22',
    soTien: 15000000,
    noiDung: 'Thu tiền lãi tiền gửi ngân hàng',
    boPhanId: '2',
    boPhanTen: 'Phòng Kế toán - Tài chính',
    dongTienId: '9',
    dongTienTen: 'Thu từ vay ngân hàng',
    taiKhoanNo: '1121',
    taiKhoanCo: '515',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Nguyễn Văn A',
    ngayTao: '2024-01-22',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-22',
    ghiChu: 'Lãi tiền gửi tháng 01/2024',
  },
  {
    id: '5',
    soPhieu: 'PT005/2024',
    loai: 'PHIEU_THU',
    ngay: '2024-01-25',
    soTien: 80000000,
    noiDung: 'Thu tiền bán hàng - Cửa hàng Minh Phát',
    doiTuongId: '3',
    doiTuongTen: 'Cửa hàng Minh Phát',
    duAnId: '3',
    duAnTen: 'Xây dựng cầu đường nội bộ',
    chuDauTuTen: 'Ban Quản lý Khu CN',
    sanPhamId: '1',
    sanPhamTen: 'Xi măng Hà Tiên PCB40',
    dongTienId: '1',
    dongTienTen: 'Thu từ bán hàng',
    taiKhoanNo: '1111',
    taiKhoanCo: '131',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Lê Văn C',
    ngayTao: '2024-01-25',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-26',
  },
  {
    id: '6',
    soPhieu: 'PT006/2024',
    loai: 'PHIEU_THU',
    ngay: '2024-01-28',
    soTien: 200000000,
    noiDung: 'Thu tiền thanh lý máy móc cũ',
    duAnId: '4',
    duAnTen: 'Lắp đặt hệ thống điện mặt trời',
    chuDauTuTen: 'Nhà máy Sản xuất DEF',
    dongTienId: '6',
    dongTienTen: 'Thu từ thanh lý TSCĐ',
    taiKhoanNo: '1111',
    taiKhoanCo: '711',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Nguyễn Văn A',
    ngayTao: '2024-01-28',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-28',
  },
  {
    id: '7',
    soPhieu: 'PT007/2024',
    loai: 'PHIEU_THU',
    ngay: '2024-02-01',
    soTien: 500000000,
    noiDung: 'Thu góp vốn cổ đông',
    dongTienId: '11',
    dongTienTen: 'Thu góp vốn',
    taiKhoanNo: '1121',
    taiKhoanCo: '411',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Nguyễn Văn A',
    ngayTao: '2024-02-01',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-02-01',
  },
];

// Quy chuẩn hạch toán cho phiếu thu
export const quyChuanPhieuThu = [
  {
    loaiGiaoDich: 'THU_TIEN_KHACH_HANG',
    tenGiaoDich: 'Thu tiền khách hàng',
    taiKhoanNo: '1111',
    taiKhoanCo: '131',
    moTa: 'Thu tiền mặt từ khách hàng',
  },
  {
    loaiGiaoDich: 'THU_TIEN_NGAN_HANG_KH',
    tenGiaoDich: 'Thu tiền khách hàng qua ngân hàng',
    taiKhoanNo: '1121',
    taiKhoanCo: '131',
    moTa: 'Thu tiền qua chuyển khoản ngân hàng',
  },
  {
    loaiGiaoDich: 'THU_TAM_UNG_HOAN',
    tenGiaoDich: 'Thu hoàn tạm ứng',
    taiKhoanNo: '1111',
    taiKhoanCo: '141',
    moTa: 'Thu tiền tạm ứng hoàn lại từ nhân viên',
  },
  {
    loaiGiaoDich: 'THU_LAI_TIEN_GUI',
    tenGiaoDich: 'Thu lãi tiền gửi',
    taiKhoanNo: '1121',
    taiKhoanCo: '515',
    moTa: 'Thu lãi tiền gửi ngân hàng',
  },
  {
    loaiGiaoDich: 'THU_KHAC',
    tenGiaoDich: 'Thu khác',
    taiKhoanNo: '1111',
    taiKhoanCo: '711',
    moTa: 'Các khoản thu khác',
  },
];

// ===== PHIẾU CHI =====

export const mockPhieuChi: ChungTu[] = [
  {
    id: 'PC1',
    soPhieu: 'PC001/2024',
    loai: 'PHIEU_CHI',
    ngay: '2024-01-10',
    soTien: 35000000,
    noiDung: 'Thanh toán tiền hàng cho NCC Đông Á',
    doiTuongId: '5',
    doiTuongTen: 'Công ty Vật liệu Xây dựng Đông Á',
    duAnId: '1',
    duAnTen: 'Xây dựng nhà máy ABC',
    chuDauTuTen: 'Công ty TNHH ABC',
    doiId: '9',
    doiTen: 'Đội thi công số 1',
    nhanVienId: 'NV001',
    nhanVienTen: 'Nguyễn Văn Hùng',
    sanPhamId: '1',
    sanPhamTen: 'Xi măng Hà Tiên PCB40',
    dongTienId: '3',
    dongTienTen: 'Chi trả nhà cung cấp',
    taiKhoanNo: '331',
    taiKhoanCo: '1111',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Nguyễn Văn A',
    ngayTao: '2024-01-10',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-10',
  },
  {
    id: 'PC2',
    soPhieu: 'PC002/2024',
    loai: 'PHIEU_CHI',
    ngay: '2024-01-12',
    soTien: 20000000,
    noiDung: 'Tạm ứng công tác phí - Nguyễn Văn Hùng',
    doiTuongId: '8',
    doiTuongTen: 'Nguyễn Văn Hùng',
    duAnId: '3',
    duAnTen: 'Xây dựng cầu đường nội bộ',
    chuDauTuTen: 'Ban Quản lý Khu CN',
    doiId: '9',
    doiTen: 'Đội thi công số 1',
    nhanVienId: 'NV001',
    nhanVienTen: 'Nguyễn Văn Hùng',
    dongTienId: '5',
    dongTienTen: 'Chi phí hoạt động',
    taiKhoanNo: '141',
    taiKhoanCo: '1111',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Nguyễn Văn A',
    ngayTao: '2024-01-12',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-12',
  },
  {
    id: 'PC3',
    soPhieu: 'PC003/2024',
    loai: 'PHIEU_CHI',
    ngay: '2024-01-15',
    soTien: 150000000,
    noiDung: 'Thanh toán lương tháng 12/2023',
    doiId: '10',
    doiTen: 'Đội thi công số 2',
    dongTienId: '4',
    dongTienTen: 'Chi lương nhân viên',
    taiKhoanNo: '334',
    taiKhoanCo: '1121',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Lê Văn C',
    ngayTao: '2024-01-15',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-15',
    ghiChu: 'Lương tháng 12/2023 cho toàn bộ nhân viên',
  },
  {
    id: 'PC4',
    soPhieu: 'PC004/2024',
    loai: 'PHIEU_CHI',
    ngay: '2024-01-18',
    soTien: 8500000,
    noiDung: 'Chi phí văn phòng phẩm tháng 01',
    boPhanId: '2',
    boPhanTen: 'Phòng Kế toán - Tài chính',
    nhanVienId: 'NV003',
    nhanVienTen: 'Trần Thị Lan',
    sanPhamId: '10',
    sanPhamTen: 'Sơn nước nội thất Dulux',
    dongTienId: '5',
    dongTienTen: 'Chi phí hoạt động',
    khoanMucId: '1',
    khoanMucTen: 'Chi phí văn phòng',
    taiKhoanNo: '642',
    taiKhoanCo: '1111',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Lê Văn C',
    ngayTao: '2024-01-18',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-19',
  },
  {
    id: 'PC5',
    soPhieu: 'PC005/2024',
    loai: 'PHIEU_CHI',
    ngay: '2024-01-20',
    soTien: 25000000,
    noiDung: 'Thanh toán tiền thuê văn phòng tháng 01',
    doiTuongId: '11',
    doiTuongTen: 'Công ty Xây dựng Phú Cường',
    boPhanId: '8',
    boPhanTen: 'Phòng Hành chính',
    dongTienId: '5',
    dongTienTen: 'Chi phí hoạt động',
    taiKhoanNo: '642',
    taiKhoanCo: '1121',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Nguyễn Văn A',
    ngayTao: '2024-01-20',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-20',
  },
  {
    id: 'PC6',
    soPhieu: 'PC006/2024',
    loai: 'PHIEU_CHI',
    ngay: '2024-01-22',
    soTien: 5000000,
    noiDung: 'Chi phí tiếp khách',
    doiId: '9',
    doiTen: 'Đội thi công số 1',
    nhanVienId: 'NV002',
    nhanVienTen: 'Lê Văn Minh',
    dongTienId: '5',
    dongTienTen: 'Chi phí hoạt động',
    taiKhoanNo: '642',
    taiKhoanCo: '1111',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Nguyễn Văn A',
    ngayTao: '2024-01-22',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-22',
  },
  {
    id: 'PC7',
    soPhieu: 'PC007/2024',
    loai: 'PHIEU_CHI',
    ngay: '2024-01-25',
    soTien: 45000000,
    noiDung: 'Chi phí vật tư công trình - Thép xây dựng',
    duAnId: '1',
    duAnTen: 'Xây dựng nhà máy ABC',
    chuDauTuTen: 'Công ty TNHH ABC',
    doiId: '9',
    doiTen: 'Đội thi công số 1',
    nhanVienId: 'NV001',
    nhanVienTen: 'Nguyễn Văn Hùng',
    sanPhamId: '2',
    sanPhamTen: 'Thép xây dựng D10',
    dongTienId: '3',
    dongTienTen: 'Chi trả nhà cung cấp',
    taiKhoanNo: '627',
    taiKhoanCo: '1111',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Lê Văn C',
    ngayTao: '2024-01-25',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-25',
  },
  {
    id: 'PC8',
    soPhieu: 'PC008/2024',
    loai: 'PHIEU_CHI',
    ngay: '2024-01-28',
    soTien: 32000000,
    noiDung: 'Chi phí nhân công công trình B',
    duAnId: '2',
    duAnTen: 'Cải tạo văn phòng XYZ',
    chuDauTuTen: 'Công ty CP XYZ',
    doiId: '10',
    doiTen: 'Đội thi công số 2',
    nhanVienId: 'NV004',
    nhanVienTen: 'Phạm Văn Đức',
    dongTienId: '4',
    dongTienTen: 'Chi lương nhân viên',
    taiKhoanNo: '622',
    taiKhoanCo: '1111',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Nguyễn Văn A',
    ngayTao: '2024-01-28',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-01-28',
  },
  {
    id: 'PC9',
    soPhieu: 'PC009/2024',
    loai: 'PHIEU_CHI',
    ngay: '2024-02-01',
    soTien: 85000000,
    noiDung: 'Mua máy móc thiết bị mới',
    duAnId: '7',
    duAnTen: 'Xây dựng nhà xưởng sản xuất',
    chuDauTuTen: 'Công ty TNHH JKL',
    doiId: '9',
    doiTen: 'Đội thi công số 1',
    nhanVienId: 'NV001',
    nhanVienTen: 'Nguyễn Văn Hùng',
    dongTienId: '7',
    dongTienTen: 'Chi mua TSCĐ',
    taiKhoanNo: '211',
    taiKhoanCo: '1121',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Lê Văn C',
    ngayTao: '2024-02-01',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-02-01',
  },
  {
    id: 'PC10',
    soPhieu: 'PC010/2024',
    loai: 'PHIEU_CHI',
    ngay: '2024-02-05',
    soTien: 30000000,
    noiDung: 'Trả nợ gốc vay ngân hàng',
    dongTienId: '10',
    dongTienTen: 'Chi trả nợ vay',
    taiKhoanNo: '341',
    taiKhoanCo: '1121',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Nguyễn Văn A',
    ngayTao: '2024-02-05',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-02-05',
  },
  {
    id: 'PC11',
    soPhieu: 'PC011/2024',
    loai: 'PHIEU_CHI',
    ngay: '2024-02-10',
    soTien: 60000000,
    noiDung: 'Chi phí đầu tư dự án mới',
    duAnId: '5',
    duAnTen: 'Xây dựng kho bãi logistics',
    chuDauTuTen: 'Công ty Logistics GHI',
    doiId: '10',
    doiTen: 'Đội thi công số 2',
    nhanVienId: 'NV004',
    nhanVienTen: 'Phạm Văn Đức',
    dongTienId: '8',
    dongTienTen: 'Chi đầu tư dự án',
    taiKhoanNo: '241',
    taiKhoanCo: '1121',
    trangThai: 'DA_DUYET',
    nguoiTao: 'Lê Văn C',
    ngayTao: '2024-02-10',
    nguoiDuyet: 'Trần Thị B',
    ngayDuyet: '2024-02-10',
  },
];

// Quy chuẩn hạch toán cho phiếu chi
export const quyChuanPhieuChi = [
  {
    loaiGiaoDich: 'CHI_TRA_NCC_TIEN_MAT',
    tenGiaoDich: 'Thanh toán nhà cung cấp (tiền mặt)',
    taiKhoanNo: '331',
    taiKhoanCo: '1111',
    moTa: 'Chi tiền mặt thanh toán cho nhà cung cấp',
  },
  {
    loaiGiaoDich: 'CHI_TRA_NCC_NGAN_HANG',
    tenGiaoDich: 'Thanh toán nhà cung cấp (ngân hàng)',
    taiKhoanNo: '331',
    taiKhoanCo: '1121',
    moTa: 'Chuyển khoản thanh toán cho nhà cung cấp',
  },
  {
    loaiGiaoDich: 'CHI_TAM_UNG',
    tenGiaoDich: 'Chi tạm ứng',
    taiKhoanNo: '141',
    taiKhoanCo: '1111',
    moTa: 'Chi tạm ứng cho nhân viên',
  },
  {
    loaiGiaoDich: 'CHI_LUONG',
    tenGiaoDich: 'Chi lương nhân viên',
    taiKhoanNo: '334',
    taiKhoanCo: '1121',
    moTa: 'Chi trả lương cho nhân viên qua ngân hàng',
  },
  {
    loaiGiaoDich: 'CHI_PHI_QLKD',
    tenGiaoDich: 'Chi phí quản lý kinh doanh',
    taiKhoanNo: '642',
    taiKhoanCo: '1111',
    moTa: 'Chi phí quản lý, văn phòng, tiếp khách...',
  },
  {
    loaiGiaoDich: 'CHI_PHI_BAN_HANG',
    tenGiaoDich: 'Chi phí bán hàng',
    taiKhoanNo: '641',
    taiKhoanCo: '1111',
    moTa: 'Chi phí quảng cáo, vận chuyển...',
  },
  {
    loaiGiaoDich: 'CHI_LAI_VAY',
    tenGiaoDich: 'Chi trả lãi vay',
    taiKhoanNo: '635',
    taiKhoanCo: '1121',
    moTa: 'Chi trả lãi vay ngân hàng',
  },
  {
    loaiGiaoDich: 'CHI_KHAC',
    tenGiaoDich: 'Chi khác',
    taiKhoanNo: '811',
    taiKhoanCo: '1111',
    moTa: 'Các khoản chi khác',
  },
];

export const trangThaiChungTu = [
  { value: 'NHAP', label: 'Nháp', color: 'default' },
  { value: 'CHO_DUYET', label: 'Chờ duyệt', color: 'processing' },
  { value: 'DA_DUYET', label: 'Đã duyệt', color: 'success' },
  { value: 'TU_CHOI', label: 'Từ chối', color: 'error' },
];
