import { SanPham } from '@/types';

export const donViOptions = [
  { value: 'CAI', label: 'Cái' },
  { value: 'CHIEC', label: 'Chiếc' },
  { value: 'BO', label: 'Bộ' },
  { value: 'HOP', label: 'Hộp' },
  { value: 'THUNG', label: 'Thùng' },
  { value: 'KG', label: 'Kg' },
  { value: 'TAN', label: 'Tấn' },
  { value: 'M', label: 'Mét' },
  { value: 'M2', label: 'M²' },
  { value: 'M3', label: 'M³' },
  { value: 'LIT', label: 'Lít' },
  { value: 'GOI', label: 'Gói' },
  { value: 'CUON', label: 'Cuộn' },
  { value: 'DICH_VU', label: 'Dịch vụ' },
];

export const nhomSanPhamOptions = [
  { value: 'VAT_TU', label: 'Vật tư' },
  { value: 'THIET_BI', label: 'Thiết bị' },
  { value: 'DICH_VU', label: 'Dịch vụ' },
  { value: 'NGUYEN_VAT_LIEU', label: 'Nguyên vật liệu' },
  { value: 'THANH_PHAM', label: 'Thành phẩm' },
  { value: 'KHAC', label: 'Khác' },
];

export const mockSanPham: SanPham[] = [
  {
    id: '1',
    ma: 'SP001',
    ten: 'Xi măng Hà Tiên PCB40',
    donVi: 'Tấn',
    giaBan: 2100000,
    moTa: 'Xi măng Portland hỗn hợp PCB40, bao 50kg',
  },
  {
    id: '2',
    ma: 'SP002',
    ten: 'Thép xây dựng D10',
    donVi: 'Tấn',
    giaBan: 15500000,
    moTa: 'Thép thanh vằn D10, tiêu chuẩn CB300-V',
  },
  {
    id: '3',
    ma: 'SP003',
    ten: 'Gạch ống 4 lỗ',
    donVi: 'Viên',
    giaBan: 1200,
    moTa: 'Gạch ống đất sét nung 4 lỗ, kích thước 8x8x18cm',
  },
  {
    id: '4',
    ma: 'SP004',
    ten: 'Cát xây dựng',
    donVi: 'M³',
    giaBan: 350000,
    moTa: 'Cát vàng xây dựng, độ mịn 2.0-2.5',
  },
  {
    id: '5',
    ma: 'SP005',
    ten: 'Đá 1x2',
    donVi: 'M³',
    giaBan: 420000,
    moTa: 'Đá dăm 1x2 xây dựng',
  },
  {
    id: '6',
    ma: 'DV001',
    ten: 'Dịch vụ tư vấn thiết kế',
    donVi: 'Dịch vụ',
    giaBan: 50000000,
    moTa: 'Dịch vụ tư vấn và lập hồ sơ thiết kế công trình',
  },
  {
    id: '7',
    ma: 'DV002',
    ten: 'Dịch vụ giám sát thi công',
    donVi: 'Dịch vụ',
    giaBan: 30000000,
    moTa: 'Dịch vụ giám sát thi công công trình xây dựng',
  },
  {
    id: '8',
    ma: 'SP006',
    ten: 'Ống nhựa PVC D90',
    donVi: 'Mét',
    giaBan: 45000,
    moTa: 'Ống nhựa PVC đường kính 90mm, độ dày 3mm',
  },
  {
    id: '9',
    ma: 'SP007',
    ten: 'Dây điện 2.5mm Cadivi',
    donVi: 'Mét',
    giaBan: 12000,
    moTa: 'Dây điện đơn Cadivi lõi đồng 2.5mm²',
  },
  {
    id: '10',
    ma: 'SP008',
    ten: 'Sơn nước nội thất Dulux',
    donVi: 'Lít',
    giaBan: 185000,
    moTa: 'Sơn nước nội thất Dulux Inspire, màu trắng',
  },
];
