// Import all master-data entities to register declare modules
import './tai-khoan.entity';
import './bo-phan.entity';
import './du-an.entity';
import './doi-tuong.entity';
import './khoan-muc.entity';
import './ngan-hang.entity';
import './san-pham.entity';
import './dong-tien.entity';
import './chu-dau-tu.entity';
import './nhom-khuyen-mai.entity';
import './nhom-quan-ly.entity';
import './loai-chung-tu.entity';
import './nhom-khoan-muc.entity';
import './loai-giao-dich.entity';
import './hop-dong.entity';
import './theo-doi-hop-dong.entity';
import './thu-tien-hop-dong.entity';
import './hoa-don-ban-ra.entity';
import './so-du-dau-ky.entity';
import './kho.entity';
import './don-vi-tinh.entity';
import './nhom-vat-tu.entity';
import './hang-hoa-vat-tu.entity';
import './ho-so-chung-tu.entity';
import './ly-do-khong-hop-le.entity';

// Re-export all entities
export * from './tai-khoan.entity';
export * from './bo-phan.entity';
export * from './du-an.entity';
export * from './doi-tuong.entity';
export * from './khoan-muc.entity';
export * from './ngan-hang.entity';
export * from './san-pham.entity';
export * from './dong-tien.entity';
export * from './chu-dau-tu.entity';
export * from './nhom-khuyen-mai.entity';
export * from './nhom-quan-ly.entity';
export * from './loai-chung-tu.entity';
export * from './nhom-khoan-muc.entity';
export * from './loai-giao-dich.entity';
export * from './hop-dong.entity';
export * from './theo-doi-hop-dong.entity';
export * from './thu-tien-hop-dong.entity';
export * from './hoa-don-ban-ra.entity';
export * from './so-du-dau-ky.entity';
export * from './kho.entity';
export * from './don-vi-tinh.entity';
export * from './nhom-vat-tu.entity';
export * from './hang-hoa-vat-tu.entity';
export * from './ho-so-chung-tu.entity';
export * from './ly-do-khong-hop-le.entity';
